name: Development

on:
  push:
    branches:
      - development

jobs:
  build_and_release:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build ipa
        run: sh scripts/archive-to-ipa.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            fpv.ipa
